@echo off
pip install astroid==2.1.0 --force-reinstall
pip install colorama==0.4.1 --force-reinstall
pip install cycler==0.10.0 --force-reinstall
pip install imageio==2.5.0 --force-reinstall
pip install isort==4.3.4 --force-reinstall
pip install kiwisolver==1.0.1 --force-reinstall
pip install lazy-object-proxy==1.3.1 --force-reinstall
pip install matplotlib==3.0.2 --force-reinstall
pip install mccabe==0.6.1 --force-reinstall
pip install numpy==1.16.1 --force-reinstall
pip install Pillow==5.4.1 --force-reinstall
pip install pylint==2.2.2 --force-reinstall
pip install pyparsing==2.3.1 --force-reinstall
pip install python-dateutil==2.8.0 --force-reinstall
pip install rope==0.12.0 --force-reinstall
pip install scipy==1.2.1 --force-reinstall
pip install six==1.12.0 --force-reinstall
pip install wrapt==1.11.1 --force-reinstall